export const LOGIN_STACK = 'LOGIN_STACK';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';

export const HOME_SCREEN = 'HOME_SCREEN';
export const APP_TAB = 'APP_TAB';

export const PRESENTIAL_STACK = 'PRESENTIAL_STACK';
export const PRESENTIAL_PAYMENT = 'PRESENTIAL_PAYMENT';
export const QR_SCREEN = 'QR_SCREEN';
export const PRESENTIAL_SUCCESS_SCREEN = 'PRESENTIAL_SUCCESS_SCREEN';

export const CARD_STACK = 'CARD_STACK';
export const CARD_LIST_SCREEN = 'CARD_LIST_SCREEN';
export const CARD_DETAIL_SCREEN = 'CARD_DETAIL_SCREEN';
export const TRANSFERS_SCREEN = 'TRANSFERS_SCREEN';
export const PAYMENTS_SCREEN = 'PAYMENTS_SCREEN';
