export const LOGIN_STACK = 'LOGIN_STACK';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN';
export const CHANGE_PASSWORD_SCREEN = 'CHANGE_PASSWORD_SCREEN';
export const SETTINGS_PROFILE_SCREEN = 'SETTINGS_PROFILE_SCREEN';
export const RESET_PASSWORD_SCREEN = 'RESET_PASSWORD_SCREEN';

export const HOME_SCREEN = 'HOME_SCREEN';
export const APP_TAB = 'APP_TAB';

export const ON_SITE_STACK = 'ON_SITE_STACK';
export const ON_SITE_PAYMENT = 'ON_SITE_PAYMENT';
export const QR_SCREEN = 'QR_SCREEN';
export const ON_SITE_SUCCESS_SCREEN = 'ON_SITE_SUCCESS_SCREEN';

export const REMOTE_STACK = 'REMOTE_STACK';
export const REMOTE_PAYMENT = 'REMOTE_PAYMENT';
export const REMOTE_CONFIRMATION_SCREEN = 'REMOTE_CONFIRMATION_SCREEN';

export const CARD_STACK = 'CARD_STACK';
export const CARD_LIST_SCREEN = 'CARD_LIST_SCREEN';
export const CARD_DETAIL_SCREEN = 'CARD_DETAIL_SCREEN';
export const TRANSFERS_SCREEN = 'TRANSFERS_SCREEN';
export const PAYMENTS_SCREEN = 'PAYMENTS_SCREEN';

export const CHARGE_DETAIL = 'CHARGE_DETAIL';
