export const LOGIN_STACK = 'LOGIN_STACK';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';

export const HOME_SCREEN = 'HOME_SCREEN';
export const APP_TAB = 'APP_TAB';

export const ON_SITE_STACK = 'ON_SITE_STACK';
export const ON_SITE_PAYMENT = 'ON_SITE_PAYMENT';
export const QR_SCREEN = 'QR_SCREEN';
export const ON_SITE_SUCCESS_SCREEN = 'ON_SITE_SUCCESS_SCREEN';

export const REMOTE_STACK = 'REMOTE_STACK';
export const REMOTE_PAYMENT = 'REMOTE_PAYMENT';

export const CARD_STACK = 'CARD_STACK';
export const CARD_LIST_SCREEN = 'CARD_LIST_SCREEN';
export const CARD_DETAIL_SCREEN = 'CARD_DETAIL_SCREEN';
export const TRANSFERS_SCREEN = 'TRANSFERS_SCREEN';
export const PAYMENTS_SCREEN = 'PAYMENTS_SCREEN';
